### ISSUE TITLE
Detailed instructions to train

### ISSUE THREAD

**Issue by arunasank** [KunZhou9646/emotional-voice-conversion-with-CycleGAN-and-CWT-for-Spectrum-and-F0#2]
Hi @KunZhou9646! Can you please write some detailed isntructions on 
1. Required datasets - quantity and datatype
2. Pre-processing data for training
3. How to train
4. How to draw inference

**Comment by KunZhou9646** [comment]
Hi, thanks for your suggestions! I have updated the readme a few days before. Now you can have a better understanding of the codes. As for the requirement of the dataset and preprocessing procedures, you can find them in our paper.
