### ISSUE TITLE
Could you please provide me the download url of the Corpus? I failed to find it.

### ISSUE THREAD

**Issue by zhaoxy0303** [KunZhou9646/emotional-voice-conversion-with-CycleGAN-and-CWT-for-Spectrum-and-F0#3]
Thank you.

**Comment by KunZhou9646** [comment]
Hi, sorry I cannot provide you with the download URL of the corpus, as the corpus we used is not publicly and belongs to other groups. We do not have the ownership of this corpus. We are really sorry about that!
If you are doing emotional voice conversion, there are a few public emotional datasets. Among them, I recommend  EmoV-DB to you, you can find it through the link below:
https://github.com/numediart/EmoV-DB
This dataset is public and can be used only for research purpose. In fact, we are also preparing an emotional speech dataset which will contain 20 speakers (10 in English and 10 in Mandarin) and 5 emotions (Neutral, happy, sad, angry and surprise). Hopefully, it will be prepared and published by the end of this year. I will let you know as long as it is published.

**Comment by psvlnandu** [comment]
> Hi, sorry I cannot provide you with the download URL of the corpus, as the corpus we used is not publicly and belongs to other groups. We do not have the ownership of this corpus. We are really sorry about that! If you are doing emotional voice conversion, there are a few public emotional datasets. Among them, I recommend EmoV-DB to you, you can find it through the link below: https://github.com/numediart/EmoV-DB This dataset is public and can be used only for research purpose. In fact, we are also preparing an emotional speech dataset which will contain 20 speakers (10 in English and 10 in Mandarin) and 5 emotions (Neutral, happy, sad, angry and surprise). Hopefully, it will be prepared and published by the end of this year. I will let you know as long as it is published.

Hi,
can you provide the link if your dataset is published?
