### ISSUE TITLE
Can you give me some suggest about tansfering neutral to sad

### ISSUE THREAD

**Issue by Scx123** [KunZhou9646/emotional-voice-conversion-with-CycleGAN-and-CWT-for-Spectrum-and-F0#7]
There seemed less changes when I performed this code about tansfering neutral to sad by Chinese.Moreover, it worked on transfering neutral to angry or happy.Can you give me some advice if you have time.

**Comment by KunZhou9646** [comment]
I suggest you have a look at the training data you used. If the main difference between neutral and sad is more about the rhythm rather than vocal attributes (including intonation),  this code may not work very well.

**Comment by Scx123** [comment]
Thank you for your reply.There is another question. Does the slient section in the data have any infulence on the results?My understanding is that it won't.

**Comment by KunZhou9646** [comment]
I do think it will affect the performance. You'd better trim the audio if there is a long silence at the beginning or the end. In my case, I didn't trim the audio since the dataset I used does not have such issues.

**Comment by Scx123** [comment]
Thank you for your answer and all the best in your work.
